# MATTRIS by Matthew Kenneth Peterson
#
# In order to execute this "Makefile" just type "make"

SOURCE	= main.c rembrandt.c gameloop.c
HEADER	= blockstruct.h scorestruct.h locknload.h
OUT	= mattris.out
CC	= gcc
LFLAGS	= -lm -lncurses


make: $(OBJS)
	$(CC) -g main.c -o $(OUT) $(LFLAGS)
